export * from './ping.controller';
export * from './facultad-departamento.controller';
export * from './departamento-facultad.controller';
export * from './proponente-trabajo-departamento.controller';
export * from './proponente-trabajo-tipo-vinculacion.controller';
export * from './departamento.controller';
export * from './facultad.controller';
export * from './proponente-trabajo.controller';
export * from './tipo-vinculacion.controller';
